### ISSUE TITLE
when adding a morgue, sometimes the result is: "✅ Success, found 0 items"

### ISSUE THREAD

**Issue by RoGGa-69** [magus/dcsseeds#5]

**Comment by magus** [comment]
Thanks for coming here to share what you encountered! Was there a morgue link you submitted that I could use to test against? Normally this happens when a run contains 0 notable items which can happen for short runs

**Comment by RoGGa-69** [comment]
I was adding morgues of wins from your other website so the morgues definitely had some randarts in them.

**Comment by magus** [comment]
do you have a link to some? I can check it again too
